coverage:
  ignore:
    - "docs"
    - "test"

  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: auto
        threshold: 20%

comment: false