name = "AeroBeams"
uuid = "4684ee71-20c3-4c77-8fc5-ebacc9f0342e"
authors = ["Luiz Pancini <luizpancini@usp.br"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
